# Generated by Django 2.2.19 on 2023-02-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230211_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='...описание не добавлено...'),
        ),
    ]
